### ISSUE TITLE
words appear again during editing of inputs / textareas

### ISSUE THREAD

**Issue by balcy** [ubports/oxide#1] opened 2017-09-08 13:53 UTC
for browser input fields / textareas (like the current one) the following happens on my Ubuntu phone (BQ Aquaris 4.5, Ubports stable 15.04 OTA1)
write the line:
foo bar
- click on the right of bar so that the blue square appears above the cursor right of bar
- click on the right of foo so that the blue square appeara above the cursor right of foo
- press space
- the line is now
foofoo  bar

could this be a problem on just my device, or a general one? It happens in the webbrowser app, but also in my other app using Ubuntu WebView.

**Comment by balcy** [comment] 2017-09-08 13:58
update: the effect can also be
foobar  bar

in general the word that has been left to the cursor before appears when you start typing again

**Comment by balcy** [comment] 2017-09-11 07:08
could also be a problem with UbuntuWebView

**Comment by balcy** [comment] 2017-09-13 17:27
I've got some more info about this after looking at it closer:
In fact the inserted string is the current word suggestion of the on-screen Ubuntu keyboard. (above the letter q)
Not as I first thought, the word left of the cursor.
I've compared the behavior to other QML input fields, e.g. of the messaging app. There each time the cursor is moved by click, the current suggestion is cleared, and thus the effect is not there.
For the HTML inputs, the last suggestion is not cleared on changing the cursor position by click. (It is cleared for pressing space for example)
If you turn off suggestions and spelling correction (system settings, language), the effect does not occur to me.

**Comment by balcy** [comment] 2017-09-13 17:31
getting the suggestion clearing into the "cursor change event" would solve the problem imho

**Comment by balcy** [comment] 2017-09-17 17:35
related:
https://bugs.launchpad.net/oxide/+bug/1384357

**Comment by balcy** [comment] 2017-10-22 10:22
also related to this: https://bugs.launchpad.net/oxide/+bug/1416460
by calling the reset() method on changing focus or cursor position the error would be gone I guess.

**Comment by NeoTheThird** [comment] 2017-10-23 16:24
duplicate of https://github.com/ubports/keyboard-component/issues/7.

**Closed as completed by NeoTheThird** 2017-10-23 16:24 UTC
Labels: duplicate
